pipeline {
    agent any
stages {
stage('Build') {
    steps {
        sh 'docker build -t baby-app -f docker/Dockerfile .'
    }
}
stage('Test') {
    steps {
        sh 'echo Testing...'
    }
}
stage('Deploy') {
    steps {
        sh 'kubectl apply -f k8s/'
    }
}
}
}
